[package]
name = "leptos-qr"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "QR Code Component for Leptos"

[package.metadata.docs.rs]
targets = ["wasm32-unknown-unknown"]

[dependencies]
fast_qr = { version = "0.12.6", features = ["svg"] }
leptos = "0.7.0"
